### ISSUE TITLE
line height is weird

### ISSUE THREAD

**Issue by Moelf** [lonkaars/typst-metalogo#2]
![image](https://github.com/user-attachments/assets/f9b55a8c-42a7-4a6c-964e-2962754fbb9f)
```typst
== Skills
- *Programming skills*: C`++`/ROOT, Julia, Python, GPU kernel programming, rr/gdb, Continuous Integration
- *Other technical skills*: HPC workflow, Container, #LaTeX, Typst
- *Languages*: English, Mandarin, Shanghainese, Japanese (elementary)
```

the middle line seems to be closer to top line than to the bottom line

**Comment by lonkaars** [comment]
This should be fixed if you upgrade to `@preview/metalogo:1.1.0`
